### ISSUE TITLE
`import setproctitle` changes `/proc/self/status`

### ISSUE THREAD

**Issue by dlucredativ** [dvarrazzo/py-setproctitle#123]
Merely importing the module changes the current process' Name in `/proc/<pid>/status`.

**Comment by dvarrazzo** [comment]
As intended, not a bug. Or better, as it was intended in the past, I am not sure that it's still the case. Did you try with the last version?

There is a trade-off to strike: certain changes either are done early in the program's lifetime, or cannot be done anymore, because some other library will tamper with the areas of memory that setproctitle uses.
