### ISSUE TITLE
Provide wheels

### ISSUE THREAD

**Issue by oberstet** [dvarrazzo/py-setproctitle#47]
In particular on Windows (and also OSX), it would be nice if `py-setproctitle` published wheels, as that make installation pain free.

**Comment by offero** [comment]
+1

**Comment by dvarrazzo** [comment]
@oberstet, @offero: will you buy me the hardware to create such packages?

**Comment by oberstet** [comment]
@dvarrazzo fair enough;)

There is a free (for open-source projects) CI packaging service here: https://www.appveyor.com/ which supports building Windows wheels: http://python-packaging-user-guide.readthedocs.org/en/latest/appveyor/

I just stumbled across this now that I searched for triggered by your question - so I don't know if it works well. But at least they claim. And I will check myself now, since we could use that for CI _testing_ on Windows ourselves (Crossbar.io / Autobahn).

**Comment by scopatz** [comment]
Also, note there is now a conda package available so you can just `conda install -c conda-forge setproctitle`.  Conda Forge uses the CI services under the hood.

**Comment by oberstet** [comment]
so a need another wheel (conda on client box) to install the wheel?  ha, pun;) if so, thx but .. no;)

**Comment by ssbarnea** [comment]
Yep the `conda-forge` method was the only one that worked for me and I had to switch my entire Python distribution in order to install setproctitle. That's clearly not so cool and I think that the package should build even on the official Python.org distribution (in addition to having published wheels).

First step, please publish Windows wheels.

**Comment by dvarrazzo** [comment]
@ssbarnea, or whoever else is concerned: please provide a patch so that I can type

    make wheels

which would use whatever online service or whatever hardware you will pay support for, and ends up with a wheel compiled and install on PyPI which then you can enjoy.

**Comment by dalito** [comment]
FYI: Windows wheels are also available on Christoph Gohlke´s site (from py27 to py 35)
http://www.lfd.uci.edu/~gohlke/pythonlibs/#setproctitle

**Comment by giampaolo** [comment]
@dvarrazzo you can automatize this as I did with psutil after I began being tired of doing it myself.
You can use appveyor. The idea is more or less the following:

- you set up appveyor so that it runs on every push (you can run tests) and also creates exe / wheels for all supported python versions
- on every successful build appveyor will store the exes / wheels as "artifacts", which really is their term for "file storage" 
- on every new release you download the exes wheels from appveyor and upload them on PYPI

I automatized all this in psutil so you can go there and take a look.

**Comment by giampaolo** [comment]
...or you can wait for me to write a blog post about it. =)

**Comment by fzumstein** [comment]
are there still plans @giampaolo to setup appveyer for building the wheels?

**Comment by dvarrazzo** [comment]
FYI, next release of setproctitle, 1.2, will be distributed with binary packages *for linux*.

Binary packages for OSX and for Windows can be created, but I will not work on them for free. If you would like to sponsor their creation you are welcome to get in touch.

**Comment by dvarrazzo** [comment]
FYI, I have set up actions to build wheel packages on linux.

They are delicious.

I see that github actions supports building window packages too: funding is welcome for windows and osx packages creation.

**Comment by dvarrazzo** [comment]
Windows packages released.

**Comment by hoffmang9** [comment]
See https://github.com/dvarrazzo/py-setproctitle/pull/96 from Chia https://chia.net

**Comment by alexprengere** [comment]
Would it be possible to release wheels for Python-3.10 as well?

**Comment by dvarrazzo** [comment]
@alexprengere  There is something rotten in the images that the CI has just produced. Packages [were created](https://github.com/dvarrazzo/py-setproctitle/actions/runs/1587268925) but I don't seem able to upload them on PyPI.

In the meantime, in other projects, I have tested with cibuildwheel and it worked nicely. So I think I will just drop our pipeline in this form and use that project instead.

**Comment by dvarrazzo** [comment]
Build system moved to cibuildwheel. It took two days. However, most wheels are built now. Enjoy setproctitle 1.2.3
